Feature/cd v241 cloud aerosol io
JCSDA/CRTMv3 pull request #37
Opened 2023-06-16 16:24 UTC by chengdang

This PR merge the v2.4.1 cloud/aerosol IO updates in to CRTM v3:

- [ ] All updates are relates to the I/O modules and no changes to coefficients/CRTM computation were made.
- [ ] Added ctest for cloud coefficient I/O ( binary and netcdf)

This PR is needed by Issac to merge the updates on cloud scheme and active sensor.
This PR can be merged into develop anytime without changing the current CRTM v3 unit tests results.

2023-06-16 16:25 UTC, chengdang commented
It seems Issac is not on CRTM v3 yet. With the pending cloud/active sensor updates, I'll add him with write permission and request a code review.

2023-06-16 19:40 UTC, imoradi commented
The changes seem fine to me so as long as the test you have added passes, which seems to be fine, then can be merged.

2023-06-16 19:41 UTC, imoradi approved these changes
The changes seem fine to me so as long as the test you have added passes, which seems to be fine, then can be merged.

2023-06-16 21:48 UTC, imoradi commented
These two lines seem to be missing in CRTM_LifeCycle.f90  but anyway I have merged this pull request into my own folk and can push them all together if you prefer that way

    IF ( PRESENT(AerosolCoeff_File ) ) Default_AerosolCoeff_File  = TRIM(ADJUSTL(AerosolCoeff_File))
    IF ( PRESENT(CloudCoeff_File   ) ) Default_CloudCoeff_File    = TRIM(ADJUSTL(CloudCoeff_File))

2023-06-16 21:54 UTC, chengdang commented
> These two lines seem to be missing in CRTM_LifeCycle.f90 but anyway I have merged this pull request into my own folk and can push them all together if you prefer that way
> 
> ```
> IF ( PRESENT(AerosolCoeff_File ) ) Default_AerosolCoeff_File  = TRIM(ADJUSTL(AerosolCoeff_File))
> IF ( PRESENT(CloudCoeff_File   ) ) Default_CloudCoeff_File    = TRIM(ADJUSTL(CloudCoeff_File))
> ```

Thank you Issac! I'll check these lines.
Let's keep them in separate PRs, and it's totally fine if you merge this branch into your fork for develop now.
I think we will merge this PR into develop before merge yours, so it'll won't be any compatibility issues when you initiate a PR.

2023-06-16 21:59 UTC, chengdang commented
The following code are added:
```
IF ( PRESENT(AerosolCoeff_File ) ) Default_AerosolCoeff_File  = TRIM(ADJUSTL(AerosolCoeff_File))
IF ( PRESENT(CloudCoeff_File   ) ) Default_CloudCoeff_File    = TRIM(ADJUSTL(CloudCoeff_File))
```

2023-06-19 13:26 UTC, BenjaminTJohnson requested changes

2023-06-19 13:26 UTC, BenjaminTJohnson commented on test/mains/unit/input_output/test_AerosolCoeff/data/AerosolCoeff.bin
This appears to be checked into the repository directly, rather than using LFS?

2023-06-19 13:26 UTC, BenjaminTJohnson commented on test/mains/unit/input_output/test_AerosolCoeff_NC/data/AerosolCoeff.nc4
Same issue here.  This should be LFS, not directly committed to the repository.

2023-06-19 13:26 UTC, BenjaminTJohnson commented on test/mains/unit/input_output/test_CloudCoeff_NC/test_cloud_coeff_io_nc.f90
> +  WRITE(*,*) 'HELLO, THIS IS A TEST CODE TO INSPECT CloudCoeff files.'
I'd prefer not to have this in code committed to develop.

2023-06-19 13:26 UTC, BenjaminTJohnson commented on test/mains/unit/input_output/test_CloudCoeff/test_cloud_coeff_io.f90
> +  WRITE(*,*) 'HELLO, THIS IS A TEST CODE TO INSPECT CloudCoefff files.'
I'd prefer not to have this in code committed to develop. (also, one too many f's)

2023-06-19 15:44 UTC, chengdang commented on test/mains/unit/input_output/test_AerosolCoeff/data/AerosolCoeff.bin
This data was saved in test folder before updates to v2.4.1 unit test. We removed it in v2.4.1 already but it was not updated in to V3, so I'm removing this file. Now it'll directly use coefficient from fix folder. 
We may want to merge the test folder updates at some point too (https://github.com/JCSDA/CRTMv3/tree/feature/v241_merge_test)

2023-06-19 15:44 UTC, chengdang commented on test/mains/unit/input_output/test_AerosolCoeff_NC/data/AerosolCoeff.nc4
Same here

2023-06-26 15:01 UTC, StegmannJCSDA requested changes

2023-06-26 15:01 UTC, StegmannJCSDA commented on src/CRTM_LifeCycle.f90
> +      WRITE(*, '("Loading cloud coefficients: ", a) ') TRIM(Default_CloudCoeff_File)
Should we have an IF-statement here that checks for `.NOT. Quiet`?

2023-06-26 15:01 UTC, StegmannJCSDA commented on src/CRTM_LifeCycle.f90
> +      WRITE(*, '("Loading aerosol coefficients: ", a) ') TRIM(Default_AerosolCoeff_File)
Should we have an IF-statement here that checks for `.NOT. Quiet`?

2023-07-17 21:54 UTC, chengdang commented
This PR is updated to include `Quiet` check before printing LUT loading information in `CRTM_LifeCycle.f90`.

This PR is also updated to reflect the recent changes in develop branch.

When `OMP_NUM_THREADS=1`, all ctests passed.
When `OMP_NUM_THREADS=4`, `test_k_matrix_ChannelSubset_iasi_metop-b` failed, this issue has been noticed earlier in V2.4.1 with issue https://github.com/JCSDA-internal/crtm/issues/277

2023-07-17 22:08 UTC, chengdang commented
All ctests passed with `OMP_NUM_THREADS=4` now, after commit https://github.com/JCSDA/CRTMv3/pull/37/commits/77d38fd2d309eab143b085f6d6c9782f6cbb2824
Not sure why.

2023-07-20 21:25 UTC, BenjaminTJohnson approved these changes

2023-07-20 21:25 UTC, merged