Merging Active Sensor and DDA Cloud Coefficients into V3
JCSDA/CRTMv3 pull request #39
Opened 2023-06-20 00:02 UTC by imoradi

## Description

This will merge active sensor module and also the code changes to be able to run CRTM using the DDA hydrometeor lookup tables.

## Issue(s) addressed

Resolves #<issue_number>

## Dependencies

List the other PRs that this PR is dependent on:

I have already merged the changes from other PR #37 into this PR.

## Impact

This should make CRTM V3.0 able to compute reflectivities and work with the DDA lookup tables.

## Checklist

- I have run this version for both active sensor to compute reflectivities and also run new cloud lookup tables. I have also compared the computed reflectivities from V2.4.1 and they are identical.

2023-06-20 21:05 UTC, StegmannJCSDA commented
@imoradi testing now.

2023-06-20 21:28 UTC, StegmannJCSDA commented
`test_AD_Active_Sensor.f90` fails to build with the following message from gfortran:
```Fortran
CRTMv3/test/mains/unit/Unit_Test/test_AD_Active_Sensor.f90:405:4:

  405 |     RTSolution_AD%Reflectivity_Attenuated(jj) = ZERO
      |    1
Error: Component to the right of a part reference with nonzero rank must not have the ALLOCATABLE attribute at (1)
CRTMv3/test/mains/unit/Unit_Test/test_AD_Active_Sensor.f90:406:4:

  406 |     RTSolution_AD%Reflectivity(jj) = ZERO
      |    1
Error: Component to the right of a part reference with nonzero rank must not have the ALLOCATABLE attribute at (1)
CRTMv3/test/mains/unit/Unit_Test/test_AD_Active_Sensor.f90:408:7:

  408 |        RTSolution_AD(ichan,:)%Reflectivity_Attenuated(jj) = ONE
      |       1
Error: Component to the right of a part reference with nonzero rank must not have the ALLOCATABLE attribute at (1)
CRTMv3/test/mains/unit/Unit_Test/test_AD_Active_Sensor.f90:410:7:

  410 |        RTSolution_AD(ichan,:)%Reflectivity(jj) = ONE
      |       1
Error: Component to the right of a part reference with nonzero rank must not have the ALLOCATABLE attribute at (1)
```

2023-06-20 21:37 UTC, imoradi commented
Are you testing it on S4? If so then can you share with me your gfort.setup

Sent from my iPhone

> On Jun 20, 2023, at 5:28 PM, StegmannJCSDA ***@***.***> wrote:
> 
> ﻿
> test_AD_Active_Sensor.f90 fails to build with the following message from gfortran:
> 
> CRTMv3/test/mains/unit/Unit_Test/test_AD_Active_Sensor.f90:405:4:
> 
>   405 |     RTSolution_AD%Reflectivity_Attenuated(jj) = ZERO
>       |    1
> Error: Component to the right of a part reference with nonzero rank must not have the ALLOCATABLE attribute at (1)
> CRTMv3/test/mains/unit/Unit_Test/test_AD_Active_Sensor.f90:406:4:
> 
>   406 |     RTSolution_AD%Reflectivity(jj) = ZERO
>       |    1
> Error: Component to the right of a part reference with nonzero rank must not have the ALLOCATABLE attribute at (1)
> CRTMv3/test/mains/unit/Unit_Test/test_AD_Active_Sensor.f90:408:7:
> 
>   408 |        RTSolution_AD(ichan,:)%Reflectivity_Attenuated(jj) = ONE
>       |       1
> Error: Component to the right of a part reference with nonzero rank must not have the ALLOCATABLE attribute at (1)
> CRTMv3/test/mains/unit/Unit_Test/test_AD_Active_Sensor.f90:410:7:
> 
>   410 |        RTSolution_AD(ichan,:)%Reflectivity(jj) = ONE
>       |       1
> Error: Component to the right of a part reference with nonzero rank must not have the ALLOCATABLE attribute at (1)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2023-06-21 15:53 UTC, StegmannJCSDA commented
> Are you testing it on S4? If so then can you share with me your gfort.setup

No, I am testing locally and I am using the ecbuild build.

2023-06-21 20:41 UTC, imoradi commented
Can someone point me to the docs showing how to load ecbuild modules for gfort on S4?

2023-06-21 21:47 UTC, imoradi commented
This is probably a gfort issues not allowing to initialize an array using an scalar (ifort is fine). Can you try test_AD_Active_Sensor.f90 to see if it compiles now?

2023-06-26 15:03 UTC, StegmannJCSDA requested changes
The PR is very extensive again and the following tests fail:
```
	 41 - test_k_matrix_Simple_atms_n21 (SEGFAULT)
	 42 - test_k_matrix_Simple_cris-fsr_n21 (SEGFAULT)
	 43 - test_k_matrix_Simple_v.abi_g18 (SEGFAULT)
	 44 - test_k_matrix_Simple_modis_aqua (SEGFAULT)
	 72 - test_adjoint_Simple_atms_n21 (Failed)
	 73 - test_adjoint_Simple_cris-fsr_n21 (Failed)
	 74 - test_adjoint_Simple_v.abi_g18 (Failed)
	 75 - test_adjoint_Simple_modis_aqua (Failed)
	 88 - test_Active_Sensor (Failed)
	 90 - test_TL_convergence_active_sensor (Failed)
```
The only ctest that hasn't been fixed yet is `test_Active_Sensor`, which fails because the following file still needs to be added to the testing data before the PR can be merged:
`./testinput/CloudCoeff_DDA_ARTS.nc4`.

2023-06-26 15:03 UTC, StegmannJCSDA commented on .gitignore
> +*.rej
We shouldn't really have to deal with `*.rej` files.

2023-06-26 15:03 UTC, StegmannJCSDA commented on src/Build/CMakeFiles/CMakeOutput.log
This file needs to be removed.

2023-06-26 15:03 UTC, StegmannJCSDA commented on src/Coefficients/CloudCoeff/CloudCoeff_Define.f90
> +      WRITE(*,'(/5x,"Press <ENTER> to view the infrared solid phase backscatteringparameter")')
There's no space in `backscatteringparameter`.

2023-07-11 01:18 UTC, BenjaminTJohnson requested changes

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/AtmScatter/CRTM_CloudScatter.f90
> +        IF ( SC(SensorIndex)%Is_Active_Sensor .and. CScat%Include_Scattering ) THEN
This use of a flag is inconsistent with:  
```
USE CRTM_SpcCoeff,            ONLY: SC, &
SpcCoeff_IsMicrowaveSensor , & 
SpcCoeff_IsInfraredSensor  , &
SpcCoeff_IsVisibleSensor   , &
SpcCoeff_IsUltravioletSensor
```

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/AtmScatter/CRTM_CloudScatter.f90
> +                                   SC(SensorIndex)%Is_Active_Sensor    , & ! Input
This should be treated exactly the same as other sensor types, such as `SpcCoeff_IsMicrowaveSensor`

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/AtmScatter/CRTM_CloudScatter.f90
> +                                   SC(SensorIndex)%Is_Active_Sensor    , & ! Input
I won't comment further, but throughout this needs to be consistent.

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/AtmScatter/CRTM_CloudScatter.f90
> +         print*, 'Cloud State not defined'
please use the built-in message system.

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/Atmosphere/CRTM_Atmosphere.f90
> +        atm_out_TL = CRTM_Atmosphere_AddLayerCopy( Atm_In_TL, 0 )
this looks like a bug fix -- was this something specific that you found?

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/Atmosphere/CRTM_Atmosphere_Define.f90
> +    REAL(fp), ALLOCATABLE :: Height(:)          ! 0:K in km
Going to need some documentation on this one:  is this height above the surface?   i.e., is the surface pressure level always Height = 0 km?   if so, I'd prefer to name it "Level_Height".

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/Build/libsrc/test/check_crtm.F90
> +       rts_K%Reflectivity(m) = ZERO
This seems inelegant compared to the above lines using broadcast to set to zero -- why was this necessary?

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/CRTM_LifeCycle.f90
> +      IF ( Default_CloudCoeff_Format == 'netCDF' ) THEN
@chengdang are you okay with these changes?

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/Atmosphere/CRTM_Atmosphere_Define.f90
> +    REAL(fp), ALLOCATABLE :: Height(:)          ! 0:K in km
Also, where is height used?  I have a concern about level height vs. layer height.

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_Active_Sensor.f90
> +      Atm%Cloud(n)%Water_Density = Atm%Cloud(n)%Water_Content / dZ_m
because it will result in division by zero here

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_Active_Sensor.f90
> +
from experience, there needs to be a check to ensure `dZ_m > 0. `

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_Active_Sensor.f90
> +  COMPLEX :: perm(SIZE(temp_K))
use `COMPLEX(fp)`

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_Active_Sensor.f90
> +  e1 = 0.404399_fp
why do some constants get `_fp` and others don't?

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_Active_Sensor.f90
> +
again check for `dZ_m > 0`

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_Active_Sensor.f90
> +    perm_re = REAL(REAL(perm))  ! Double REAL is required to avoud issues with GNU Fortran
what is the issue?  I've never seen this before.

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_Active_Sensor.f90
> +    ! Arguments
all subroutines should start with `implicit none`

2023-07-11 01:18 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_Active_Sensor.f90
> +    P1 = (M6_MM6 * Wavelength_m**4.0_fp) / (PI**5.0_fp * Kw_2)
where is `M6_MM6` defined?

2023-07-11 01:19 UTC, BenjaminTJohnson commented
@imoradi finished the first round of review, I haven't tested the code yet.

2023-07-11 04:01 UTC, imoradi commented on src/AtmScatter/CRTM_CloudScatter.f90
> +        IF ( SC(SensorIndex)%Is_Active_Sensor .and. CScat%Include_Scattering ) THEN
Yes we discussed this when merging into V2.4.1 - basically the active sensors can be MW, IR or anything so we need to see whether a sensor is MW/IR/etc first then active or passive.

2023-07-11 04:02 UTC, imoradi commented on src/AtmScatter/CRTM_CloudScatter.f90
> +                                   SC(SensorIndex)%Is_Active_Sensor    , & ! Input
Please see my previous comment. Active sensors still need to be one of the other kinds.

2023-07-11 04:06 UTC, imoradi commented on src/AtmScatter/CRTM_CloudScatter.f90
> +         print*, 'Cloud State not defined'
Fixed

2023-07-11 04:08 UTC, imoradi commented on src/Atmosphere/CRTM_Atmosphere.f90
> +        atm_out_TL = CRTM_Atmosphere_AddLayerCopy( Atm_In_TL, 0 )
In the active module we don't want CRTM to mess with the input layers so I have added this flag to ensure that the output reflectivities are at the same level as the input profiles.

2023-07-11 04:10 UTC, imoradi commented on src/RTSolution/CRTM_Active_Sensor.f90
> +  e1 = 0.404399_fp
added _fp to other decimals

2023-07-11 04:15 UTC, imoradi commented on src/RTSolution/CRTM_Active_Sensor.f90
> +
as long as the pressure is different then dz_m will not be zero and the profiles pressure levels are checked before hands. Why do we want to double check when it should have been checked from the first place? It is easy to put a statement here but just want to make sure it is really necessary.

2023-07-11 04:17 UTC, imoradi commented on src/RTSolution/CRTM_Active_Sensor.f90
> +    perm_re = REAL(REAL(perm))  ! Double REAL is required to avoud issues with GNU Fortran
See this link https://gcc.gnu.org/onlinedocs/gcc-3.4.6/g77/REAL_0028_0029-and-AIMAG_0028_0029-of-Complex.html

2023-07-11 04:23 UTC, imoradi commented on src/RTSolution/CRTM_Active_Sensor.f90
> +    ! Arguments
I have included IMPLICIT NONE in the top of the module and that should cover all the subroutines. Isn't it? I believe that is the case but if not then will it to each subroutines. I also checked other modules of CRTM and it has only being added once - see also this link https://stackoverflow.com/questions/24337413/where-to-put-implicit-none-in-fortran

2023-07-11 04:24 UTC, imoradi commented on src/RTSolution/CRTM_Active_Sensor.f90
> +    P1 = (M6_MM6 * Wavelength_m**4.0_fp) / (PI**5.0_fp * Kw_2)
In the same file as private variables only accessible to the module subroutines.

2023-07-11 04:26 UTC, imoradi commented
> @imoradi finished the first round of review, I haven't tested the code yet.

Thanks @BenjaminTJohnson - I have responded to your comments. Some of the points here were also discussed when merging this into V2.4.1.

2023-07-17 13:05 UTC, BenjaminTJohnson commented
In subroutine (`Get_Cloud_Opt_MW`):
```
crtm/src/AtmScatter/CRTM_CloudScatter.f90(1406): error #6404: This name does not have a type, and must have an explicit type.   [ERROR_STATUS]
          Error_Status = FAILURE
----------^
```
It's missing:
``` 
INTEGER :: Error_Status 
<...>
 Error_Status = SUCCESS
<...>
```

2023-07-17 13:08 UTC, BenjaminTJohnson commented
@imoradi This would be much easier to merge if you created a feature branch in the CRTMv3 repository instead of trying to merge from your forked repository, that way I could hotfix your feature branch for minor issues (such as above) to accelerate the process.

2023-07-20 21:27 UTC, BenjaminTJohnson commented
@imoradi please merge the latest CRTMv3 develop, and resolve the noted conflicts. 
Thanks!

2023-07-22 07:17 UTC, imoradi commented
> @imoradi please merge the latest CRTMv3 develop, and resolve the noted conflicts.

Unfortunately the entire "src/CRTM_Forward_Module.f90" needs once again to be manually checked and merged as changes from the features that were opened after I made this PR are scattered all over this file. I already merged one of the PRs that fixes the aerosol coefficient issue. This was the issue preventing me from using my CRTMv3.0 fork for the JEDI developments.

2023-10-18 16:29 UTC, merged