Feature/cd rt sout net cdf
JCSDA/CRTMv3 pull request #66
Opened 2023-09-11 17:14 UTC by chengdang

## Description
This PR add new module to write CRTM output RTS into netCDF format: 
`CRTM_RTSolution_WriteFile_netCDF`
https://github.com/JCSDA/CRTMv3/blob/6cd0398a56687f8371f1a0c320710d5e5aa1d8cf/src/RTSolution/CRTM_RTSolution_Define.f90#L1223

To use `CRTM_RTSolution_WriteFile_netCDF`, uncomment code block in `check_crtm.f90`:
https://github.com/JCSDA/CRTMv3/blob/6cd0398a56687f8371f1a0c320710d5e5aa1d8cf/src/Build/libsrc/test/check_crtm.F90#L393

There is no code changes to `src/RTSolution/Common_RTSolution.f90`, but a lot of auto space deletion due to code editor.

## Issue(s) addressed
Resolves #<62>

## Dependencies
None

## Impact
None

2023-09-13 14:07 UTC, BenjaminTJohnson requested changes

2023-09-13 14:07 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_RTSolution_Define.f90
> +  PUBLIC :: CRTM_RTSolution_WriteFile_netCDF
writefile_netcdf should live within CRTM_RTSolution_WriteFile -- you could pass an optional flag for it to determine if it's netCDF or not.    I would not at all be against just defaulting to netCDF as the standard output format and removing the binary option.

2023-09-13 14:07 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_RTSolution_Define.f90
> +  ! Output netCDF attributes
How are these being used?

2023-09-13 14:07 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_RTSolution_Define.f90
> +    REAL(fp) :: SSA_Max                 = ZERO  ! Max Single Scattering Albedo in the profile
What is this used for?

2023-09-13 14:07 UTC, BenjaminTJohnson commented on src/RTSolution/CRTM_RTSolution_Define.f90
> +    REAL(fp) :: Stokes(4)
What are the contents of this?

2023-09-13 21:44 UTC, chengdang commented on src/RTSolution/CRTM_RTSolution_Define.f90
> +  PUBLIC :: CRTM_RTSolution_WriteFile_netCDF
I can do that. Currently the `CRTM_RTSolution_WriteFile` is build as Binary output interface only. Let me try to modify it.

2023-09-14 00:18 UTC, chengdang commented
Updated `CRTM_RTSolution_WriteFile` to write CRTM RTSolution object files in either Binary or NetCDF format.
The original `CRTM_RTSolution_WriteFile` has been modified as function `CRTM_RTSolution_WriteFile_Binary`. 
Users may continue use  `CRTM_RTSolution_WriteFile` for binary outputs, no changes to codes is needed.

2023-09-22 21:43 UTC, chengdang commented
@BenjaminTJohnson This branch is ready for merge for netCDF output only. We should perhaps discuss more on the ctests related updates, see https://github.com/JCSDA/CRTMv3/issues/72.

All ctests passed but occasionally the channel subset test fails:
`test_k_matrix_ChannelSubset_iasi_metop-b `
I don't see any code change that may impact this mysterious test.

2023-10-03 14:48 UTC, merged